### ISSUE TITLE
addTask + unique id

### ISSUE THREAD

**Issue by brstgt** [wcgallego/pecl-gearman#10]
When I do NOT pass the "unique id" parameter to "addTask", when executing multiple tasks in parallel, only a single task is exexuted. It seems that a non-null value is implied, when omitting the unique id param.
I can reliably reproduce this behaviour with our system tests.
Actually I can only observe this behaviour in an FPM environment. Everything seems to work on CLI.
I was able to reproduce it by running the same tasks with a system test running in PHPUnit in CLI and another system test that tests our API via HTTP. The first tests run successfully, the latter produces the mentioned issue.

The gist shows a part of our message queue implementation running multiple tasks: https://gist.github.com/brstgt/aa68bca091c15438a592

**Comment by wcgallego** [comment]
Just to confirm - this ran correctly in PHP 5, @brstgt, but fails to in PHP 7?

Not sure why that might be immediately. The code for executing based on unique id should be the same. Do you have any ini or env settings in your Apache context that might not be equivalent in the cli?

I can certainly set up an apache instance on my test environment and replicate if you have code demonstrating it! This sounds like an interesting one

**Comment by brstgt** [comment]
Hi,

I recognized this when running our system tests with a php7 test machine.
The tests that run within phpunit hat no problem but the system tests that
test our API via HTTP produced that problem.
The tested model does simply create multiple sized versions of a photo by
running multiple gearman tasks in parallel.
I would love to share a code snippet but I cannot share our whole
repository and these tests heavily depend on our platform. I can share a
snippet but you won't be able to run that directly.

2016-03-12 16:45 GMT+01:00 Will notifications@github.com:

**Comment by wcgallego** [comment]
I think this has been fixed with #11. When you're able, can give a look?

**Comment by wcgallego** [comment]
Closing this out. If it's still an issue, please reopen @brstgt
