### ISSUE TITLE
Leaving default values for addServer() results in jobs not being processed

### ISSUE THREAD

**Issue by vladnis** [wcgallego/pecl-gearman#16]
Hi,

When running the example from http://gearman.org/examples/multi-query/, if I leave the addServer function to default values the worker and client seem to not comunicate and jobs are left unprocessed.

Example was run with PHP 7.0.4-6+deb.sury.org~xenial+3 (cli) ( NTS )

sudo netstat -peanut | grep 'php'

worker ==>  tcp        0      0 127.0.0.1:38210         127.0.0.1:4730          ESTABLISHED 1000       115403      23802/php
client  ==>  tcp        0      0 127.0.0.1:38214          127.0.0.1:4730          ESTABLISHED 1000       116803      23810/php  

If I manually set $worker->addServer('127.0.0.1', 4730); the example runs without problem.

Changeset tested: 9e32a58ca8a33caba7d3b45a49357f6e801e3199

**Comment by wcgallego** [comment]
hey @vladnis,

I'm having some trouble replicating on my instance. The logic of this code hasn't changed from php 5 to php 7 - are you able to replicate this on a php 5 instance?

My steps were:
1) starting gearmand in daemon mode with default values
2) copied code exactly as is from multi query examples
3) in one window, run:
php worker.php
4) in another, run:
php client.php

It'll take a few seconds then outputs:
Fetching...
Got user info in: 9.17 seconds:
string(59) "The user requested (joe@joe.com) is 7 feet tall and awesome"
string(56) "The user (joe@joe.com) is 1 degree away from Kevin Bacon"
string(43) "The user (joe@joe.com) has no posts, sorry!"

What version of the underlying gearman library are you using, @vladnis ?

**Comment by vladnis** [comment]
I am using gearman 1.0.6. Is this the newest stable release?

**Comment by wcgallego** [comment]
No, you can find the latest releases for gearmand and libgearman here:

https://launchpad.net/gearmand/

I'm running 1.1.12 for my testing. I suggest trying to upgrade next, as I believe that the default values are tweaked in a later release, though I forget which.

Also, were you experiencing this same behavior with PHP 5?

**Comment by wcgallego** [comment]
Closing this for now, as it looks like it might be an issue with the underlying c lib.

@vladnis, if upgrading libgearman doesn't fix this, please reopen and we can discuss further. Thanks!
