### ISSUE TITLE
SEGFAULT when Exception is not caught in Worker function

### ISSUE THREAD

**Issue by brstgt** [wcgallego/pecl-gearman#17]
`while (true) {
    $w = new GearmanWorker();
    $w->addServer();
    $w->addFunction('somequeue', function () {
        throw new Exception('lala');
    });
    $w->work();
}
`

Will constantly crash the worker. Catching and logging the Exception works.

**Comment by wcgallego** [comment]
Hey @brstgt, looking into this more. Some questions
- Got a core dump? Those are often helpful
- Are you queuing up any jobs along with this or just running this stand alone?
- What version of libgearman are you using?
- Are you doing anything more than just dropping this in a file and running php worker.php?

any other info you think might be useful in adding to this would be great

**Comment by wcgallego** [comment]
Ok, I think there's actually two problems at play:

1) the GearmanWorker::addFunction call isn't properly handling anonymous functions

2) This mishandling is falling into the exception state, but the exception handling isn't working correctly either, which is causing the seg fault

I can replicate this so I'll get to it fixing this up. Thanks for figuring this out and sorry for the disruption

**Comment by wcgallego** [comment]
Hey @brstgt, I've pushed a change which I think fixes the above seg fault, at least how it was replicating on my system. Please give the latest a grab and test it out. Thanks again.

**Comment by brstgt** [comment]
Good job :) Seems to work!
