### ISSUE TITLE
Unable to compile extension

### ISSUE THREAD

**Issue by Wouter0100** [wcgallego/pecl-gearman#2]
I'm unable to compile because of too less arguments, see [this gist](https://gist.github.com/Wouter0100/292ce553988cc8b0f4d2).

It seems the last arg of zend_register_internal_class_ex has a default value set (is that a default value?) but isn't recognized.

Is this a known issue?

**Comment by wcgallego** [comment]
Hey @Wouter0100, this isn't known. It's been compiling for me ok.

Can you give me some info about your environment? compilers, operating system, etc.

Edit: Whoops, that's what I get for looking at an old version of my code in the wrong dir :) Editing out some confusing notes I had before. Env/OS would help though, thanks!

**Comment by Wouter0100** [comment]
Hmm, it's on Ubuntu 15.04 with DirectAdmin installed ([PHP 5.6](http://php5.wouter0100.nl/) and [PHP 7.0](http://php7.wouter0100.nl/)). I'm compiling it against PHP 7.0 (of course). I've tried again, but still no luck.

**Comment by wcgallego** [comment]
did you phpize this first as PHP 7 or PHP 5?

via http://lxr.php.net/xref/PHP_7_0/Zend/zend_API.h#637, RETURN_STRING only takes one argument in PHP 7, but in lower version (like here in 5.6 http://lxr.php.net/s?refs=RETURN_STRING&project=PHP_5_6) it takes 2. My guess is you're compiling this against a PHP 5.x installation

**Comment by wcgallego** [comment]
I think this is resolved - I'm like 99.9% sure it's compilation against the wrong version of PHP.

Feel free to open if this persists and I can help out!

**Comment by caiohasouza** [comment]
Hello @wcgallego,

I too have this problem, my environment:
Centos 6.8
PHP 7.0.7 (cli) (built: May 25 2016 18:36:46) ( NTS )

In ./configure:

....
/tmp/pecl-gearman/php_gearman.c:3865: error: ‘gearman_task_obj’ has no member named ‘zdata’
/tmp/pecl-gearman/php_gearman.c: At top level:
/tmp/pecl-gearman/php_gearman.c:3871: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘gearman_task_obj_new_ex’
/tmp/pecl-gearman/php_gearman.c:3906: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘**attribute**’ before ‘gearman_task_obj_new’
/tmp/pecl-gearman/php_gearman.c: In function ‘zm_startup_gearman’:
/tmp/pecl-gearman/php_gearman.c:4306: error: ‘gearman_client_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4308: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4314: error: ‘gearman_task_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4316: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4322: error: ‘gearman_worker_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4324: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4330: error: ‘gearman_job_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4332: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4339: error: too many arguments to function ‘zend_register_internal_class_ex’
make: *\* [php_gearman.lo] Erro 1

Do you can help me?

Att;
