### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by stevehill1981** [wcgallego/pecl-gearman#21]
Are there any outstanding issues that would prevent tagging a release?

I've just built a Homebrew formula to install the extension based on this repo (PR here: https://github.com/Homebrew/homebrew-php/pull/3120), but it's not passing all of its checks as I'm relying on the master branch rather than a stable version.

If further testing is required, I'm happy to assist - really think it'd be great to get this extension out in the wild.

**Comment by wcgallego** [comment]
The outstanding issue is the segfault/memory leak I'm currently cleaning up. It's affecting anyone who passes in a reference to a method in a class as the added function for a Gearman worker.

I've fixed the segfault, but am working on the mem leak part of it. I've got a reproducible case. This is on my radar.

**Comment by stevehill1981** [comment]
Great, thanks :)

**Comment by javian** [comment]
@wcgallego are you making any progress on this issue ?

**Comment by wcgallego** [comment]
Hey @javian and @stephenorr,

thanks for patience here. With the help of one of my coworkers, we tracked down the memleak (a circular reference, see issue #19).

I'll be putting together some of the merge commits and tagging a proper release now that I feel (more) confident the code isn't breaking everyone else's.

**Comment by stevehill1981** [comment]
Awesome, thanks @wcgallego.

**Comment by wcgallego** [comment]
Apologies for slowness - life gets in the way of our code :P

I've created branch 2.0.1 which should be considered the current stable branch. Thanks for keeping me honest here!

**Comment by stevehill1981** [comment]
@wcgallego - Is there any chance you could tag 2.0.1 as well please? As I'm relying on it for my Homebrew formula, it's handy to have a known fixed version to install.

**Comment by wcgallego** [comment]
Ah, sorry about that!

https://github.com/wcgallego/pecl-gearman/tree/gearman-2.0.1

**Comment by stevehill1981** [comment]
Wonderful :)
