### ISSUE TITLE
Unable to compile extension

### ISSUE THREAD

**Issue by caiohasouza** [wcgallego/pecl-gearman#23]
Hello

I have same problem the issue (https://github.com/wcgallego/pecl-gearman/issues/2), my environment:
Centos 6.8
PHP 7.0.7 (cli) (built: May 25 2016 18:36:46) ( NTS )

In make:

....
/tmp/pecl-gearman/php_gearman.c:3865: error: ‘gearman_task_obj’ has no member named ‘zdata’
/tmp/pecl-gearman/php_gearman.c: At top level:
/tmp/pecl-gearman/php_gearman.c:3871: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘attribute’ before ‘gearman_task_obj_new_ex’
/tmp/pecl-gearman/php_gearman.c:3906: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘attribute’ before ‘gearman_task_obj_new’
/tmp/pecl-gearman/php_gearman.c: In function ‘zm_startup_gearman’:
/tmp/pecl-gearman/php_gearman.c:4306: error: ‘gearman_client_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4308: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4314: error: ‘gearman_task_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4316: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4322: error: ‘gearman_worker_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4324: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4330: error: ‘gearman_job_obj_new’ undeclared (first use in this function)
/tmp/pecl-gearman/php_gearman.c:4332: error: too many arguments to function ‘zend_register_internal_class_ex’
/tmp/pecl-gearman/php_gearman.c:4339: error: too many arguments to function ‘zend_register_internal_class_ex’
make: *\* [php_gearman.lo] Erro 1

Do you can help me?

Att;

**Comment by xalopp** [comment]
I just tested on CentOS 6.8 with PHP7 from Webtactic and Gearman from EPEL, and it's compiling without failure and all tests are passing.

Sure you're using phpize of PHP7 and having the gearman devel files properly installed?

```
[vagrant@localhost vagrant-pecl-gearman]$ cat /etc/redhat-release 
CentOS release 6.8 (Final)
[vagrant@localhost vagrant-pecl-gearman]$ rpm -q -a | grep -E 'gearman|php'
libgearman-1.1.8-2.el6.x86_64
libgearman-devel-1.1.8-2.el6.x86_64
php70w-devel-7.0.7-1.w6.x86_64
gearmand-1.1.8-2.el6.x86_64
php70w-cli-7.0.7-1.w6.x86_64
php70w-common-7.0.7-1.w6.x86_64
[vagrant@localhost vagrant-pecl-gearman]$ phpize 
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
```

**Comment by caiohasouza** [comment]
Hello, @xalopp,

I cloned the repo again and everything was fine.

Thank you.

Att;

**Comment by xalopp** [comment]
@xdexter you're welcome.
