### ISSUE TITLE
PHP7 GearmanClient::doBackground returns a fixed size string padded with NULLs

### ISSUE THREAD

**Issue by xalopp** [wcgallego/pecl-gearman#24]
When I create a job with GearmanClient::doBackground with PHP7, the function will return a job handle which has a fixed size of 63 bytes, padded with NULLs. So it's not really a string, but a fixed sized area of bytes.

```
$jobHandle = $germanClient->doBackground($jobName, $workload);

strpos($jobHandle, null) = 26
strlen($jobHandle) = 63
```

PHP5 returns a proper PHP-String with proper size.

I'm running German version  1.1.11.

PR is in progress.

**Comment by wcgallego** [comment]
Thanks for the fix @xalopp! Sorry for the delay - was out of country.

**Comment by xalopp** [comment]
@wcgallego no problem. Thanks for merging 🎉
