### ISSUE TITLE
Extension is not thread safe

### ISSUE THREAD

**Issue by xalopp** [wcgallego/pecl-gearman#28]
`tests/gearman_client_011.phpt`  might fail, when the test suite is run with a thread safe PHP, as provided by Travis CI, see https://github.com/travis-ci/travis-ci/issues/2800

Should I create a PR which explains this situation in the README?
Or are there any plans to make this extensions TS?

**Comment by wcgallego** [comment]
hey @xalopp, thanks for chiming in on this. I'll be honest, making this extension thread safe is beyond my capabilities tweaking the extension, so as of now I can't make claims as to doing so in the future. Smarter engineers than I can certainly tackle that and I'd be all for it!

I think explaining such in the README is a solid idea, if only so there's a caveat for such.

**Comment by xalopp** [comment]
@wcgallego should I open a PR  which adds a `LIMITATIONS` section to the README file?

**Comment by keyurdg** [comment]
@xalopp The test 011 is faulty. I fixed it in commit 360b12cfe952bfdda0b70ae0f8f37cdfda8f94bb. 

The extension is thread-safe, so PR #30 is not needed.

**Comment by xalopp** [comment]
@keyurdg awesome! Test runs with plain travis-ci PHP (zts build)
