### ISSUE TITLE
Removing forked status

### ISSUE THREAD

**Issue by javian** [wcgallego/pecl-gearman#33]
Thanks for tagging the 2.0.1 release and I'll make sure it gets included into homebrew-php some time this week. The audit check for homebrew formulas also check the forked status of the repository. If this is the main repo for gearman today would you mind removing the forked status of the repo ?

**Comment by wcgallego** [comment]
I think we're going to merge this back in with hjr's, not mariano's. Working on that!

**Comment by remicollet** [comment]
Any news about merging with Herman Radtke sources, and then doing an official PECL release ?

**Comment by wcgallego** [comment]
hey @remicollet, been focused on cleaning up rather than official pecl release.

Herman's not involved in working on the extension anymore, so we decided it'd be better to split this out into a github repo that's not connected to a specific user.

Just finished a big sweep of adding tests and splitting up files last night, so I'll try to get to that this weekend.

**Comment by wcgallego** [comment]
ok! Step one is done. Forked status is removed here.

Before we get an official realease, I'd like for this to have a permanent home, though, so we don't have to switch it again later. I've emailed the owners of https://github.com/gearman to see if they'd like to include the pecl-gearman as one of their repos. If they agree, I'll transfer over. Otherwise, I'll set up a standalone pecl-gearman-dev account and transfer to that.

**Comment by remicollet** [comment]
Notice than another solution is to ask for repo creation on git.php.net (mirrored on https://github.com/php/ for PR). This allow imply using pecl bug tracker (which already [exists](https://bugs.php.net/search.php?cmd=display&status=Open&package_name[]=gearman))

**Comment by wcgallego** [comment]
good call, @remicollet! What's the best path to asking for such? Should I just hit up someone in #php.pecl on Freenode?

**Comment by remicollet** [comment]
Have to ask on pecl-devl ML (and if too long, ping some admin on IRC), probably need approval from current owner, but IIUC, he is ok with that.

**Comment by wcgallego** [comment]
Sorry for delay. Tyrael was kind enough to set this up on git.php.net at http://git.php.net/?p=pecl/networking/gearman.git;a=summary (see https://github.com/hjr3/pecl-gearman/issues/12#issuecomment-266323621)

I'll close this up one I've actually gotten the code migrated there

**Comment by tuupola** [comment]
Any progress with this? PECL still has 1.1.2 from year 2013.

**Comment by wcgallego** [comment]
Hey all,

sorry this has taken an absurd amount of time. I have creds for php.net and the repo is set up. I unfortunately don't have the karma to push yet though!

Here's to me earning it. I'll start cleaning up some Gearman docs to see if I can gain it the hard way 😝

**Comment by cdekok** [comment]
Any chance of this still happening? It would be nice if it's available on PECL

**Comment by codayblue** [comment]
Any update on this? The company I am working with is thinking about using this extension. How can I help if there is a way?

**Comment by djsipe** [comment]
For those looking to use this extension in PHP 7, but unsure about how to install it.  I have this snippet for installing it using the official PHP Docker image:

```
# GEARMAN
# Download Gearman PECL extension for Gearman supporting PHP 7
RUN apt-get -y --allow-unauthenticated install \
    libgearman-dev
RUN cd /tmp \
    && git clone https://github.com/wcgallego/pecl-gearman.git \
    && cd pecl-gearman \
    && git checkout gearman-2.0.3 \
    && phpize \
    && ./configure \
    && make -j$(nproc) \
    && make install \
    && rm -r /tmp/pecl-gearman \
    && docker-php-ext-enable gearman
```

**Comment by wcgallego** [comment]
Nearly 4 years later (oof) it's finally living in a reasonable location

https://github.com/php/pecl-networking-gearman

Sorry for the troubles everyone! Better care taking awaits in its new home
