### ISSUE TITLE
pecl-gearman-master/php_gearman_task.h:48:26: warning: inline function ‘gearman_task_fetch_object’ declared but never defined

### ISSUE THREAD

**Issue by ce5ca11a0** [wcgallego/pecl-gearman#34]
This is a follow up on my post:

> Using wcgallego/pecl-gearman I get a "/usr/lib/php/20151012/gearman.so: undefined symbol: gearman_task_fetch_object" when calling **addTask** on the client. When using **doNormal**, I get "Segmentation fault (core dumped)" on the worker after every third call to a queue (job). I just upgraded to Ubuntu 16 (amd64) and PHP7. All worked OK in Ubuntu 14 and PHP5.3

When I compiled it from source using "make install", I get:

/bin/bash /pecl-gearman-master/libtool --mode=compile cc  -I. -I/pecl-gearman-master -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall   -c /pecl-gearman-master/php_gearman.c -o php_gearman.lo 
libtool: compile:  cc -I. -I/pecl-gearman-master -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -c /pecl-gearman-master/php_gearman.c  -fPIC -DPIC -o .libs/php_gearman.o
**In file included from /pecl-gearman-master/php_gearman.c:21:0:
/pecl-gearman-master/php_gearman_task.h:48:26: warning: inline function ‘gearman_task_fetch_object’ declared but never defined
 inline gearman_task_obj *gearman_task_fetch_object(zend_object *obj);**
                          ^
/bin/bash /pecl-gearman-master/libtool --mode=compile cc  -I. -I/pecl-gearman-master -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall   -c /pecl-gearman-master/php_gearman_client.c -o php_gearman_client.lo 
libtool: compile:  cc -I. -I/pecl-gearman-master -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -c /pecl-gearman-master/php_gearman_client.c  -fPIC -DPIC -o .libs/php_gearman_client.o
/bin/bash /pecl-gearman-master/libtool --mode=compile cc  -I. -I/pecl-gearman-master -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall   -c /pecl-gearman-master/php_gearman_task.c -o php_gearman_task.lo 
libtool: compile:  cc -I. -I/pecl-gearman-master -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib -DHAVE_CONFIG_H -g -O2 -Wall -c /pecl-gearman-master/php_gearman_task.c  -fPIC -DPIC -o .libs/php_gearman_task.o
/bin/bash /pecl-gearman-master/libtool --mode=link cc -DPHP_ATOM_INC -I/pecl-gearman-master/include -I/pecl-gearman-master/main -I/pecl-gearman-master -I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib  -DHAVE_CONFIG_H  -g -O2 -Wall   -o gearman.la -export-dynamic -avoid-version -prefer-pic -module -rpath /pecl-gearman-master/modules  php_gearman.lo php_gearman_client.lo php_gearman_task.lo -lgearman -lgearman -lgearman -lgearman
libtool: link: rm -fr  .libs/gearman.la .libs/gearman.lai .libs/gearman.so
libtool: link: cc -shared  -fPIC -DPIC  .libs/php_gearman.o .libs/php_gearman_client.o .libs/php_gearman_task.o   -lgearman  -g -O2   -Wl,-soname -Wl,gearman.so -o .libs/gearman.so
libtool: link: ( cd ".libs" && rm -f "gearman.la" && ln -s "../gearman.la" "gearman.la" )
/bin/bash /pecl-gearman-master/libtool --mode=install cp ./gearman.la /pecl-gearman-master/modules
libtool: install: cp ./.libs/gearman.so /pecl-gearman-master/modules/gearman.so
libtool: install: cp ./.libs/gearman.lai /pecl-gearman-master/modules/gearman.la
## libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:$JRE_HOME/bin:/sbin" ldconfig -n /pecl-gearman-master/modules

Libraries have been installed in:
   /pecl-gearman-master/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
- add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
   during execution
- add LIBDIR to the 'LD_RUN_PATH' environment variable
   during linking
- use the '-Wl,-rpath -Wl,LIBDIR' linker flag
- have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
## more information, such as the ld(1) and ld.so(8) manual pages.

Installing shared extensions:     /usr/lib/php/20151012/

**Comment by wcgallego** [comment]
Yup, this is what i get for trying to clean things up. Sorry about that! This merge should fix:

https://github.com/wcgallego/pecl-gearman/commit/a2932e3c03ebf7bf0d686269b67ff19538d2192e

lemme know if it works for you?

**Comment by wcgallego** [comment]
Waiting on a response back, I'm going to close this for now. I believe this to be fixed.

If it's still broken, please reopen and add any additional info. Thanks!
