### ISSUE TITLE
Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0

### ISSUE THREAD

**Issue by lougreenwood** [wcgallego/pecl-gearman#35]
Hi :)

I'm currently attempting to build the Gearman PHP extension on an Alpine Linux based PHP7 docker image.

I'm using the official package from here - https://hub.docker.com/_/php/ (7.0.10-fpm-alpine).

I've built the extension using the following commands:

```
RUN cd / \
    && git clone --depth=1 git://github.com/wcgallego/pecl-gearman.git \
    && cd pecl-gearman \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && docker-php-ext-enable gearman
```

(docker-php-ext-enable is a helper script provided a as part of the docker PHP image)

The problem I'm finding is that I get the following error after building the extension:

```
Build complete.
Don't forget to run 'make test'.

Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20151012/
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0
/usr/local/bin/docker-php-ext-enable: cd: line 4: can't cd to

Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0
/usr/local/lib/php/extensions/no-debug-non-zts-20151012
```

If I remove the `docker-php-ext-enable gearman` and then run `php --info | grep gearman`, I see a similar output returned from PHP:

```
# php --info | grep gearman
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0
```

I did some digging on the subject and found that it 'could' be related to Alpine Line not including glibc, however after installing a glib combat library for Alpine (Alpine uses musl libc instead of glib) I still get the same issue.

Any ideas? Alpine Linux is now the default bistro for Docker, so any ideas tr help would be greatly appreciated! :)

Thanks

**Comment by lougreenwood** [comment]
I just noticed that when I do php --info | grep gearman, I get this output instead:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so' - Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gearman.so: gearman_task_fetch_object: symbol not found in Unknown on line 0

PWD => /pecl-gearman/modules
$_SERVER['PWD'] => /pecl-gearman/modules
```

Note the PWD & $_SERVER_PWD - could this be related?

**Comment by vtky** [comment]
@lougreenwood you may want to have a look at my pull request if you need your issue fixed urgently

**Comment by lougreenwood** [comment]
@vtky, perfect, I'll take a look, thanks - I had about 1 day left before I needed to rip up my Alpine linux image and move to Ubuntu just because of this error - fingers crossed :)

**Comment by lougreenwood** [comment]
@vtky seems to work for me too - thanks 👍

**Comment by wcgallego** [comment]
Cool, looks like it's fixed (thanks @vtky for jumping in!)

closing.
