### ISSUE TITLE
PHP 7 - Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kylephp** [wcgallego/pecl-gearman#40]
Hi,
I've got the above error when trying with 2.0.1
Seems a random bug and hard to reproduce b/c it did not happen quite often. I've got this from /var/log/messages: 

> php[37105]: segfault at 75e ip 000000000061428d sp 00007fff1cac8ec0 error 4 in php[400000+33e000]
# 

System info:
- CentOS 6.8
- Libgearman 1.1.8
- PHP 7.0.10

My compiled extension included the fix on https://github.com/wcgallego/pecl-gearman/commit/3ef16f9b5cc105ad970ef050c743909316d83f47
Any idea how to debug the crash on the extension?

**Comment by wcgallego** [comment]
Hey @kylephp, the OS/versions are a good start and I appreciate linking to the commit that broke. Do you have example code to reproduce reliably? The log message doesn't really give me much (those memory addresses won't be consistent system to system or even run to run).

Can you enable core dumps and attache a core dump file?

**Comment by wcgallego** [comment]
@kylephp please reopen when you can attach a core dump. Thanks

**Comment by kylephp** [comment]
@wcgallego Thanks for your reply. I have been debugging for a long time. Now I can reproduce it using the repository's example:
https://github.com/wcgallego/pecl-gearman/blob/master/examples/reverse_worker.php#L23 

Just change that line to `$gmworker->addFunction("reverse", "reverse_fn", new stdClass());`

On the client code, I have a loop to make it call the worker continuously:

> <?php
$gmc= new GearmanClient();
$gmc->addServer('gearman.dev.php');

$gmc->setCreatedCallback("reverse_created");
$gmc->setStatusCallback("reverse_status");
$gmc->setCompleteCallback("reverse_complete");
$gmc->setFailCallback("reverse_fail");

while (1) {
    $task= $gmc->addTask("reverse", "this is a test", NULL);
    if (! $gmc->runTasks())
    {
        echo "ERROR " . $gmc->error() . "\n";
        exit;
    }
    echo "DONE\n";
}

function reverse_created($task)
{
    echo "CREATED: " . $task->jobHandle() . "\n";
}

function reverse_status($task)
{
    echo "STATUS: " . $task->jobHandle() . " - " . $task->taskNumerator() . 
         "/" . $task->taskDenominator() . "\n";
}

function reverse_complete($task)
{
    echo "COMPLETE: " . $task->jobHandle() . "\n";
}

function reverse_fail($task)
{
    echo "FAILED: " . $task->jobHandle() . "\n";
}
?>

Now, run them on different terminals, you will get this on the worker: `Segmentation fault (core dumped)`

**Comment by kylephp** [comment]
I can't see any option to re-open the issue on my side

**Comment by wcgallego** [comment]
Thanks Kyle! Sorry this has been plaguing you, but super appreciate the replicable work flow.

I'm a little tied up at the moment, but I'll jump into this as soon as I'm able. Hang tight!

**Comment by kylephp** [comment]
Thanks @wcgallego!
Btw, I have just looked through the closed issues and maybe this has been fixed in master branch but not released yet?
https://github.com/wcgallego/pecl-gearman/issues/49
I will try to compile the extension from master branch and test it again

**Comment by kylephp** [comment]
Tested with new compiled extension and it works!
Maybe you need to grab a new bug fix release @wcgallego
