### ISSUE TITLE
PHP_GEARMAN_CLIENT_RET_OK

### ISSUE THREAD

**Issue by darioguarascio** [wcgallego/pecl-gearman#41]
I think the latest commit introduced a new bug:
while compiling:
```
/root/pecl-gearman/php_gearman_worker.c: In function 'zif_gearman_worker_wait':
/root/pecl-gearman/php_gearman_worker.c:266:9: warning: implicit declaration of function 'PHP_GEARMAN_CLIENT_RET_OK' [-Wimplicit-function-declaration]
         if (! PHP_GEARMAN_CLIENT_RET_OK(obj->ret)) {

```

And workers now exit with:

`php: symbol lookup error: /usr/lib/php/20151012/gearman.so: undefined symbol: PHP_GEARMAN_CLIENT_RET_OK
`

**Comment by galicante** [comment]
+1

**Comment by wcgallego** [comment]
Thanks for the heads up on this. Will take a look.

Just remember to use the tags as master is bleeding edge and shouldn't be considered prod worthy yet.

Better still, if you can put together a test for this, all the better

**Comment by wcgallego** [comment]
Ah, nm on test, probably not really a testable thing. But I'll hop right on this

**Comment by wcgallego** [comment]
Easy fix, just needed to include php_gearman_client.h in php_gearman_worker.h.

Give the latest on master a pull and see if it works?

**Comment by galicante** [comment]
Master looks ok now. 
I'll switch on tags, thx :+1:
