### ISSUE TITLE
tests/gearman_tasks_integration_test_002.phpt breaks with gearmand 1.0.6

### ISSUE THREAD

**Issue by xalopp** [wcgallego/pecl-gearman#42]
Running the test suite with `make test`  for the current master (bbc426f5609269de13a0edbea0a821c0c0b952f3), the test `gearman_tasks_integration_test_002.phpt` will fail, with gearmand 1.0.6. With Gearman 1.1.x the test is doing fine.

```
FAIL Test Gearman worker methods [tests/gearman_tasks_integration_test_002.phpt]
```
Content of  `cat gearman_tasks_integration_test_002.log`
```
---- EXPECTED OUTPUT
Start
Exception: unhandled
Fail
Complete: done
returnCode: 0
clearCallbacks: true
Done
---- ACTUAL OUTPUT
Start
Exception: unhandled
Complete: exception
Fail
Complete: done
returnCode: 0
clearCallbacks: true
Done
---- FAILED
```

This has been tested on Ubuntu 14.04.1 (trusty) see https://travis-ci.org/xalopp/pecl-gearman/builds/175834537, CentOS 6.8.

Looks like that `$job->sendException("unhandled");` in [gearman_tasks_integration_test_002.phpt line 36](https://github.com/wcgallego/pecl-gearman/blob/master/tests/gearman_tasks_integration_test_002.phpt#L36) triggers both, Exception and Complete Callback.

**Comment by xalopp** [comment]
The behavior changed with  55e7ccc7ea66a73c15a099210657384ff7e5dfbd
@wcgallego are you using gearmand-1.1.x or gearmand-1.0.x  for testing?

**Comment by wcgallego** [comment]
Hey @xalopp, I've been using gearmand 1.1.2 for my work (slightly out of date). 

As someone who isn't using an older version, I'm curious about adoption/current use of 1.0.x branch, as the last commit to it was 2012. I'd like to say 1.1.x should be min requirement and reflect such in documentation, but willing to hear pushback. The current maintainer says 1.1.x is still devel based on the naming scheme, though.

Thoughts/feelings?

**Comment by xalopp** [comment]
@wcgallego
How about to stick on what it's declared in the README? 😄 
```
For the 2.0.* versions, testing is done against libgearman v1.1.8
```
Maybe it's fine to change that to `v1.1.8 or greater`


I'll will create a PR for that 😄
