### ISSUE TITLE
runTasks method requires a parameter

### ISSUE THREAD

**Issue by kemalbaynu3** [wcgallego/pecl-gearman#45]
Hi,

I was playing around with PHP7 and I stumbled upon with this different behaviour.

In PHP5 with Gearman Client, runTasks method doesn't need a parameter.
`Method [  public method runTasks ] {
      - Parameters [0] {
      }
}`

But in this fork, it requires a parameter called 'data'. 
`Method [  public method runTasks ] {
      - Parameters [1] {
        Parameter #0 [  $data ]
      }
}`

Could you please explain to me why we need this parameter?

Thanks.

**Comment by wcgallego** [comment]
Thanks @kemalbaynu3, looks like a slip when I was tweaking some stuff. I'll put in a fix and push a minor version soon.

**Comment by wcgallego** [comment]
gearman-2.0.3 should fix that. Let me know if you see any others! Thanks

**Comment by kemalbaynu3** [comment]
Thanks!
