### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method GearmanClient::do()

### ISSUE THREAD

**Issue by mfiyalka** [wcgallego/pecl-gearman#48]
I use MAMP PRO 3.5 and PHP 7.0.0
I installed the extension according to instructions

The function `gearman_version()` works, but not working `GearmanClient()`:
```
<?php
$client = new GearmanClient();
$data = 'test';
$res = $client->do('function_test', $data);
echo $res;
```
Error:
```
Fatal error: Uncaught Error: Call to undefined method GearmanClient::do() in /Users/mfiyalka/Desktop/test.php on line 5
Error: Call to undefined method GearmanClient::do() in /Users/mfiyalka/Desktop/test.php on line 5
Call Stack:
    0.0030     352736   1. {main}() /Users/mfiyalka/Desktop/test.php:0
```
Help me, please.

**Comment by marcguyer** [comment]
I can't help you other than suggest that you also confirm the version of the lib you're using. What does your php_info say for Gearman extension version and libgearman version?

**Comment by mfiyalka** [comment]
I found a mistake. I use a method that is outdated :)
Thanks.
