### ISSUE TITLE
does not work with gearman 1.1.15 GEARMAN_UNKNOWN_STATE

### ISSUE THREAD

**Issue by mamciek** [wcgallego/pecl-gearman#51]
When installed with libgearman 1.1.15 then invoking GearmanClient::doBackground ends with GEARMAN_UNKNOWN_STATE error

**Comment by wcgallego** [comment]
hey @mamciek, apologies this hasn't gotten more attention. Hoping to clean up a few of these over the next few weeks. Have you tried this with a newer version of libgearman in the mean time?

**Comment by wcgallego** [comment]
I'm going to close this issue up. I believe it to be an issue with the core library and not the pecl extension. As 1.1.15 isn't the latest and greatest, I'd suggest upgrading the core first and seeing if you can still replicate the issue.

If you think this is in error or it warrants more investigation, please reopen and we can discuss! Thanks
