### ISSUE TITLE
MySQL queue does not work

### ISSUE THREAD

**Issue by xrn** [wcgallego/pecl-gearman#56]
Hi,
One the beginning I would like to say - great job Will!

I used gearman around one year and I started to test new options. Today I tried to use MySQL queue type. I ran my job server (version 1.1.18) using this command:

> usr/local/sbin/gearmand -l /var/log/gearman-job-server/gearman.log --verbose=NOTICE --queue-type=MySQL --mysql-host=localhost --mysql-port=3306 --mysql-user=XXX --mysql-password=YYY --mysql-db=gearman --mysql-table=queue

When I use command from a terminal

> gearman -f testq -b payload

Everything looks fine and in my table, I can see

> mysql> select * from queue;
> +--------------------------------------+---------------+----------+---------+-------------+
> | unique_key                           | function_name | priority | data    | when_to_run |
> +--------------------------------------+---------------+----------+---------+-------------+
> | 3272d074-302e-11e8-a9b9-de9976efe999 | testq         |        1 | payload |           0 |
> +--------------------------------------+---------------+----------+---------+-------------+
> 1 row in set (0.00 sec)

But task sent from PHP client (current repo version - but when I use echo gearman_version(); I get 1.0.6) working but not showing in the table.

**Comment by wcgallego** [comment]
Good catch, on both the version and the task. I don't use tasks as often in my day to day, so thanks for picking these up. Seems like I have two bugs to fix here :) Will take a look

**Comment by wcgallego** [comment]
P.S. - can you double check what version of gearman lib you're using before I dig too deep?

I've got 1.1.12 here. Have you tried upgrading that to seem if it resolves the underlying issues?

[~]> php -r 'echo gearman_version(). PHP_EOL;'
1.1.12

**Comment by wcgallego** [comment]
Also, if you could include explicitly the code snippet in PHP you're using, that would helpful.

As an aside (I'm trying to remember all my gearman internals specifics, it's been a while), gearman_version() prints out the libgearman version (the underlying lib), not what pecl version it is. For that, you can use phpinfo() and look for "extension version" in the gearman section

**Comment by xrn** [comment]
1. You have 100%  right - I update all from the beginning and now after
> php -r 'echo gearman_version(). PHP_EOL;' i get 1.1.18

2. Code is 100% simple 

Client:
```
$client= new GearmanClient();
$client->addServer("127.0.0.1",4730);

$job_result = $client->doNormal("reverse", "Hello World!");
```

Worker:
```
$worker= new GearmanWorker();
$worker->addServer("127.0.0.1",4730);
$worker->addFunction("reverse", "my_reverse_function");
while ($worker->work());

function my_reverse_function($job)
{
  return strrev($job->workload());
}
```

**Comment by xrn** [comment]
Ok this is my bad. It is working! But in MySQL i can only find Background tasks (maybe quque is working in this way, but this is strage)

> gearman -f testq -b payload

This command have -b flag, when i used 

```
$job_result = $client->doBackground("reverse", "Hello World!");
```
I get
```
mysql> select * from queue;
+--------------------------------------+---------------+----------+--------------+-------------+
| unique_key                           | function_name | priority | data         | when_to_run |
+--------------------------------------+---------------+----------+--------------+-------------+
| 6d8585e6-3810-11e8-aa60-de9976efe999 | testq         |        1 | payload      |           0 |
| a087c7ba-3810-11e8-aa60-de9976efe999 | reverse       |        1 | Hello World! |           0 |
| a8dd7752-3810-11e8-aa60-de9976efe999 | reverse       |        1 | Hello World! |           0 |
+--------------------------------------+---------------+----------+--------------+-------------+
3 rows in set (0.00 sec)
```
