### ISSUE TITLE
GearmanClient::addServer and GearmanClient::addServers aren't assuming setupExceptionHandler as optional

### ISSUE THREAD

**Issue by lockland** [wcgallego/pecl-gearman#61]
The last parameter (setupExceptionHandler) added to GearmanClient::addServer and GearmanClient::addServers has been required instead of to be optional as described on the documentation. When these methods are invoked without set the parameter the message below is shown.

`Method GearmanClient::addServers() invoked with 1 parameter, 2 required`

**Comment by fishfacemcgee** [comment]
@lockland Out of curiosity, did you find a solution to this or did you close it due to inactivity?

**Comment by lockland** [comment]
@fishfacemcgee I was getting this errors with a phpunit mock on the unit tests, so after got the master branch, compiled it and ran the project tests I could see everything is OK and the mentioned problem could be on phpunit and not on pecl-gearman, however I didn't run my tests with that compiled version. 
The interesting thing is that I wasn't getting this error before have the php updated to version 7.1.19, but I need to debug more to find the root cause.
