### ISSUE TITLE
register method in GearmanWorker seems not working as expected

### ISSUE THREAD

**Issue by leunggamciu** [wcgallego/pecl-gearman#62]
```php
//client.php

$client = new GearmanClient;
$client->addServer('127.0.0.1');
$client->doNormal('foo', 'workload');
```

```php
//worker.php

function foo($job) {
    //
}

$worker = new GearmanWorker;
$worker->addServer('127.0.0.1');
$worker->register('foo');
while ($worker->work()) {
}
```

The worker crash with following message after receiving a job: 

> PHP Warning:  GearmanWorker::work(): gearman_worker_work(GEARMAN_INVALID_FUNCTION_NAME) Neither a gearman_worker_fn, or gearman_function_fn callback was supplied -> libgearman/worker.cc:

Not sure if I am using it in this way correctly. 

PHP version: 7.2.7
extension version: 2.0.4
libgearman version: 1.0.6

**Comment by wcgallego** [comment]
hey @leunggamciu, I would highly suggest upgrading to a newer version of libgearman. Work has been done against v1.1.8 for the 2.0.* branch of the pecl

https://github.com/wcgallego/pecl-gearman/blob/master/README#L14

If you upgrade and are still having difficulties, please reopen and we can address from there. Thanks!

**Comment by leunggamciu** [comment]
thanks for the reply @wcgallego,  the problem still exists after upgrading libgearman to 1.1.18

**Comment by wcgallego** [comment]
Hey @leunggamciu, the problem isn't gearman, it's the php code you're supplying. This is what you want for the worker:

```
<?php
$worker = new GearmanWorker();
$worker->addServer('127.0.0.1');
$worker->register('foo');

$worker->addFunction('foo', function($job) {
                                print "In the function, workload is: " .
                                print_r($job, true) . PHP_EOL;
                        }); 

while ($worker->work()) {
}
```

**Comment by leunggamciu** [comment]
Hello @wcgallego, I think I misunderstand the `register` method. I found that like many other examples  
on the website, your code may still works after removing `$worker->register('foo')`. So i'm wonder if you could explain it in more detail.

**Comment by wcgallego** [comment]
Sure. The register method is for listening for specific job names, with the second param being a timeout to listen for jobs (optional). The addFunction method takes for its first param a function name and for its second a callback to execute when that function is received.

http://php.net/manual/en/gearmanworker.register.php
http://php.net/manual/en/gearmanworker.addfunction.php
