### ISSUE TITLE
add new releases to PECL 

### ISSUE THREAD

**Issue by Mararok** [wcgallego/pecl-gearman#65]
Can you send new 2.* version to PECL ?
I'm using php 7.* and now I compiled that ext  in https://github.com/SAREhub/Servitiom/blob/doctrine_experment/api/Dockerfile 
It will be wonderful if I can download it from PECL :)

**Comment by wcgallego** [comment]
Hi @Mararok, you're not wrong to pester me on this. It needs to get done, full stop.

There's a ticket already open for this work, #33. So I'll be closing this one. Sorry for delay
