### ISSUE TITLE
Uncaught Error: Class 'GearmanClient' not found

### ISSUE THREAD

**Issue by dl-lewis** [wcgallego/pecl-gearman#68]
When trying to set up a test on a freshly installed pecl-gearman, it appears the worker works, but the client cannot be found.

We're using PHP 7 and the latest Gearman server:
libgearman version => 1.1.18

The .so is referenced in both the cli and apache ini files.

**Comment by marcguyer** [comment]
This sounds like a problem with your environment. Are you using CLI or Apache or both? What does `php -i | grep gearman` say? What about `phpinfo()` output gearman section?

**Comment by dl-lewis** [comment]
This was my fault, actually, thanks for responding. There was an .ini I didn't know about lurking around.
