### ISSUE TITLE
Release a new version from latest master with PHP 7.4 fixes

### ISSUE THREAD

**Issue by prupert** [wcgallego/pecl-gearman#75]
As you are aware of the latest released version (2.0.6, 05-09-2019) does not work with PHP 7.4. I know this project is not under active development, but it would be great if you could release a new version based on the current master with the PHP 7.4 fixes. This enables package maintainers such as Remi to follow up and build and ship packages of the pecl-gearman extension for PHP 7.4.

**Comment by wcgallego** [comment]
This feels like a good time to do a cut over.

Rasmus has been kind enough to set up https://github.com/php/pecl-networking-gearman for future pecl-gearman work. Redirecting this ticket there is a good start and is a forcing function for others who are making the switch in other places in their codebase.

If you'd be so kind to make the ask there, I'd appreciate it and I think you all will get better maintenance that i've been able to afford

**Comment by keyurdg** [comment]
Thank you for taking care of gearman all these years @wcgallego!

**Comment by tuupola** [comment]
Awesome news, I still use gearman with couple of projects. Also thanks for the maintenance in the past years @wcgallego!
