### ISSUE TITLE
 config.m4. 

### ISSUE THREAD

**Issue by karborator** [wcgallego/pecl-gearman#8]
phpize
Cannot find config.m4. 
Make sure that you run '/usr/bin/phpize' in the top level source directory of the module

Ubuntu 14.04

**Comment by wcgallego** [comment]
config.m4 is in the root dir of the package. I'm not sure why it would fail to find it.

https://github.com/wcgallego/pecl-gearman/blob/master/config.m4

Are you running this in the correct directory?

**Comment by wcgallego** [comment]
This seems like it won't fix. Closing.
