### ISSUE TITLE
Segfault when creating multiple GearmanClient instances

### ISSUE THREAD

**Issue by brstgt** [wcgallego/pecl-gearman#9]
I was able to create a segfault, when I use a new GearmanClient object for every new job.
The case was reliably reproducible. Unfortunately the project is very complex, so I cannot paste just a few lines of code to produce the issue. The segfault happened about the 4th/5th time i did a "doBackground".
After having refactored our message queue to use a single GearmanClient instance all over a single PHP request, the segfault went away.

I hope that helps a little bit.

**Comment by wcgallego** [comment]
hey @brstgt, this does, thanks. Glad you're at least in a workable state until this gets fixed.

My guess is a lot of these issues are all related. If you are ever able to reproduce in a standalone, please send my way!

Should I push some fixes, would your code base be set in such a way to test with reusing GearmanClient again? I'm happy to keep the issue open until there's a resolution, but if you're ok, I can close this and focus on the other issues.

**Comment by brstgt** [comment]
If you push new commits, just let me know, so we of course can run some
tests with the "old" environment.

2016-03-12 13:13 GMT+01:00 Will notifications@github.com:
